### PR TITLE
Add dependabot

### PR DESCRIPTION
**Pull request by NobodyXu**
Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>

### CODE REVIEW

**Comment by Nemo157** [comment]
In my experience dependabot is not useful for libraries, and results in a lot of overhead as it creates PR after PR (I see far too many repos on github with dozens of open dependabot PRs).

There is one thing I think could be useful in this space, being notified on new _major_ versions of libraries; but that doesn't appear to be something dependabot supports.

**Comment by NobodyXu** [comment]
I've used dependabot on other library crates such as [openssh](https://github.com/openssh-rust/openssh/pulls?q=is%3Apr+author%3Aapp%2Fdependabot) and it only generates a PR on new major ver of dependencies.

**Comment by Nemo157** [comment]
Interesting, maybe they changed that behavior since merging into github.

Could you add [`rebase-strategy: "disabled"`](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#rebase-strategy) as the unnecessary rebasing it does doesn't work well with bors; then I'll give it a test.

**Comment by NobodyXu** [comment]
> Interesting, maybe they changed that behavior since merging into github.
> 
> Could you add [`rebase-strategy: "disabled"`](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#rebase-strategy) as the unnecessary rebasing it does doesn't work well with bors; then I'll give it a test.

@Nemo157 Done!

**Pull request closed without merging**
